web/backend/django/django-crud/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    # path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/create/', views.comment_create, name='comment_content'),
    path('<int:article_pk>/comments/<int:comment_pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like/', views.like, name='like')
]

web/backend/django/django-crud/crud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articles import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('hashtags/<int:hashtag_pk>/', views.hashtag, name='hashtag'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/backend/django/django-crud/articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit
from django.conf import settings

# Create your models here.
# 1. 모델(스키마) 정의
# 데이터베이스 테이블을 정의하고,
# 각각의 컬럼(필드) 정의

class HashTag(models.Model):
    content = models.TextField(unique=True)
    def __str__(self):
        return self.content


class Article(models.Model):
    # id : integer 자동으로 정의(Primary Key)
    # 아래의 코드가 생략되어있음
    # id = models.AutoField(primary_key=True) -> Integer 값이 자동으로 하나씩 증가(AUTOINCREMENT)
    # CharField - 필수인자로 max_length 지정
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    # ImageSpecField : Input 하나만 받고 처리해서 저장
    # ProcessedImageField : Input 받은 것을 처리해서 저장
    # resize to fill : 300*300
    # resize to fit : 긴쪽을(너비 혹은 높이) 300에 맞추고 비율에 맞게 자름
    image_thumbnail = ProcessedImageField(
                                processors=[ResizeToFit(300, 300)],
                                format='JPEG',
                                options={'quality': 80}
                                )
    # DateTimeField
    #   auto_now_add : 생성시 자동으로 저장
    #   auto_now : 수정시마다 자동으로 저장
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # settings.AUTH_USER_MODEL : 'accounts.User' (str)
    # 아직 accounts app이 안불러와져 있을경우 에러가 발생할수 있으므로 사용해준다
    like_users = models.ManyToManyField(
                            settings.AUTH_USER_MODEL,
                            related_name='like_articles',
                            blank=True
                            )

    hashtags = models.ManyToManyField(
                            HashTag,
                            blank=True
                            )
                            

    def __str__(self):
        return f'<{self.id}> : {self.title}'

class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # on_delete
    # 1. CASCADE : 글이 삭제되었을 때 모든 댓글을 삭제
    # 2. PROTECT : 댓글이 존재하면 글 삭제 안됨.
    # 3. SET_NULL : 글이 삭제되면 NULL로 치환(NOT NULL일 경우 옵션 사용X)
    # 4. SET_DEFAULT : 디폴트 값으로 치환.

# models.py : python 클래스 정의
#           : 모델 설계도
# makemigrations : migration 파일 생성
#           : DB 설계도 작성
# migrate : migration 파일 DB 반영

web/backend/django/django-crud/articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ('user', 'hashtags', )


class CommentForm(forms.ModelForm):
    content = forms.CharField(max_length=140)
    class Meta:
        model = Comment
        exclude = ('article', 'user', )




# class ArticleForm(forms.ModelForm):
#     # 위젯 설정 2.
#     title = forms.CharField(
#         max_length=10, 
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'placeholder': '제목을 입력바랍니다.'
#             }
#         )
#     )
#     class Meta:
#         model = Article
#         fields = '__all__'
        # fields = ('title', ...) 추가
        # exclude = ('title', ...) 제거

# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=1, 
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'placeholder': '제목을 입력바랍니다.'
#             }
#         )
#     )
#     content = forms.CharField(
#         # label 내용 수정
#         label='내용',
#         # Django form에서 HTML 속성 지정 -> widget
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'my-content',
#                 'placeholder': '내용을 입력바랍니다.',
#                 'rows': 5,
#                 'cols': 60
#             }
#         )
#     ) 

web/backend/django/django-crud/articles/views.py
from IPython import embed
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.http import HttpResponseForbidden, HttpResponse
from django.core.exceptions import PermissionDenied
from django.views.decorators.http import require_POST
# from accounts.models import User
from django.contrib.auth import get_user_model
from .forms import ArticleForm, CommentForm
from .models import Article, Comment, HashTag

# Create your views here.
def index(request):
    articles = Article.objects.order_by('-id')
    # embed()
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/index.html', context)

# def new(request):
#     return render(request, 'articles/new.html')

@login_required
def create(request):
    if request.method == 'POST':
        # embed()
    # POST 요청 -> 검증 및 저장
        article_form = ArticleForm(request.POST, request.FILES)
        # embed()
        if article_form.is_valid():
        # 검증에 성공하면 저장하고,
            # title = article_form.cleaned_data.get('title')
            # content = article_form.cleaned_data.get('content')
            # article = Article(title=title, content=content)
            article = article_form.save(commit=False)
            article.user = request.user # user 인스턴스!
            article.save()
            for word in article.content.split():
                if word[0] == '#':
                    # 만들어진 값인지 있던 값인지 확인해줘서 튜플형태로 표시해준다.
                    # try:
                    #     hashtag = HashTag.objects.get(content=word)
                    # except:
                    #     hashtag = HashTag.objects.creat(content=word)
                    # 와 같이 동작하는 것을 줄여서 쓴것
                    hashtag, created = HashTag.objects.get_or_create(content=word)
                    # if HashTag.objects.filter(content=word).exists():
                    #     HashTag.objects.get(content=word)
                    # if word[1:] in article.hashtags.all():
                    #     hashtag = HashTag.objects.get(content=word[1:])
                    #     article.hashtags.add(hashtag)
                    # else:
                    #     hashtag = HashTag.objects.creat(content=word[1:])
                    article.hashtags.add(hashtag)
            # redirect
            return redirect('articles:detail', article.pk)
    else:
    # GET 요청 -> Form
        article_form = ArticleForm()
    # GET -> 비어있는 Form context
    # POST -> 검증 실패시 에러메세지와 입력값 채워진 Form context
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html', context)

def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context = {
        'article' : article,
        'comments' : comments,
        'comment_form' : comment_form
    }
    return render(request, 'articles/detail.html', context)
    
from django.views.decorators.http import require_POST

@require_POST
@login_required
def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if article.user == request.user:
        article.delete()
        return redirect('articles:index')
    else:
        raise PermissionDenied

# def edit(request, article_pk):
#     article = Article.objects.get(pk=article_pk)
#     context = {
#         'article' : article,
#     }
#     return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    article = Article.get_object_or_494(pk=article_pk)
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, instance=article)
        if article_form.is_valid():
            article = article_form.save()
            # 해시태그 수정
            article.hashtags.clear()
            for word in article.content.split():
                if word[0] == '#':
                    hashtag, created = HashTag.objects.get_or_create(content=word)
                    article.hashtags.add(hashtag)
            return redirect('articles:detail', article_pk)
    else:
        article_form = ArticleForm(instance=article)
    context = {
        'article_form' : article_form,
    }
    return render(request, 'articles/form.html', context)

@require_POST
def comment_create(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        # 1. modelform에 사용자 입력값 넣고
        comment_form = CommentForm(request.POST)
        # 2. 검증하고,
        if comment_form.is_valid():
        # 3. 맞으면 저장!
            # 3-1. 사용자 입력값으로 comment instance 생성 (저장은 X)
            comment = comment_form.save(commit=False)
            # 3-2. FK 넣고 저장
            comment.article = article
            comment.user = request.user
            comment.save()
        # 4. return redirect
        else:
            messages.success(request, '댓글이 형식이 맞지 않습니다.')
        return redirect('articles:detail', article_pk)
    else:
        return HttpResponse('Unauthorized', status=401)

    # comment = Comment()
    # comment.content = request.POST.get('content')
    # comment.article = article
    # comment.save()
    # return redirect('articles:detail', article_pk)

@require_POST
def comment_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
        # messages.add_message(request, messages.INFO, '댓글이 삭제 되었습니다.')
        messages.success(request, '댓글이 삭제되었습니다.')
        return redirect('articles:detail', article_pk)
    else:
        return HttpResponseForbidden()

@login_required
def like(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # 좋아요를 누른적이 있다면?
    # article.like_users.filter() 를 써서 확인하면서 할 수 있다. => get()을 쓰면 없을때 오류가 발생하므로 반드시 filter로
    # if article.like_users.filter(id=request.user.id).exist(): 로 써도 똑같음
    if request.user in article.like_users.all():
        # 좋아요 취소 로직
        article.like_users.remove(request.user)
    # 아니면
    else:
        # 좋아요 로직
        article.like_users.add(request.user)
    return redirect('articles:detail', article_pk)

def hashtag(request, hashtag_pk):
    hashtag = get_object_or_404(HashTag, pk=hashtag_pk)
    context = {
        'hashtag': hashtag
    }
    return render(request, 'articles/hashtag.html', context)

web/backend/django/django-crud/articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!--
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  -->
  <title>게시판</title>
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <script src="https://kit.fontawesome.com/93f188e0ea.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
</head>

<body>
{% include '_navbar.html' %}
  <div class="container">
    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">
      {{ message }}
      </div>
      {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="{% static 'bootstrap/css/bootstrap.min.js' %}"></script>
  <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script> -->
</body>

</html>

web/backend/django/django-crud/articles/templates/articles/create.html
{% extends 'articles/base.html' %}
{% block body %}
  <h1>게시판에 오신걸 환영합니다.</h1>
  <p>{{ article.id }}번째 글이 작성되었습니다.</p>
{% endblock %}

web/backend/django/django-crud/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %} {% comment %} load 는 반드시 해당 템플릿 안에서 해줘야함 {% endcomment %}
{% block body %}
{% if article.image %}
<img src="{{ article.image.url }}" alt="{{ article.image.name }}">
{% endif %}
<h1>{{ article.id }}번글</h1>
<h2>{{ article.title }}</h2>
<h2>{{ article.user }}</h2>
<h3>작성일자 : {{ article.created_at }}</h3>
<h3>수정일자 : {{ article.updated_at }}</h3>
<hr>
{% load hashtag %}
<p>{{ article|make_link|safe }}</p>
<p>{{ article.like_users.count }}명이 이 글을 좋아합니다.</p>
<a href="{% url 'articles:like' article.pk %}">
{% if user in article.like_users.all %}
<i class="fas fa-heart fa-2x" style="color: red"></i>
{% else %}
<i class="far fa-heart"></i>
{% endif %}
</a>
<!-- a tag : GET -->
<a href="{% url 'articles:index' %}">목록으로</a>
{% if article.user == user %}
<a href="{% url 'articles:update' article.pk %}">수정하기</a>
<a href="{% url 'articles:delete' article.pk %}">[X]</a>
<form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('진짜 지울래?')">
    {% csrf_token %}
    <input type="submit" value="삭제">
</form>
{% endif %}
<hr>
<h3>댓글 작성</h3>
<h4>댓글 수: {{ comments.count }}</h4>
<form action="{% url 'articles:comment_content' article.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
<hr>
<h3>댓글</h3>
{% for comment in comments %}
<li>{{ comment.content }}</li>
<li>{{ comment.created_at }}</li>
<a href="{% url 'articles:comment_delete' article.pk comment.pk %}">[X]</a>
<hr>
{% empty %}
<h3>댓글이 없습니다.</h3>
{% endfor %}
{% endblock %}

web/backend/django/django-crud/articles/templates/articles/edit.html
{% extends 'articles/base.html' %}
{% block body %}
  <h1>글 수정하기</h1>
  <form action="{% url 'articles:update' article.pk %}" method='POST'>
  {% csrf_token %}
    제목 : <input type="text" name="title" id="title" value="{{ article.title }}"><br>
    내용 : <textarea name="content" id="content">{{ article.content }}</textarea>
    <input type="submit" value="Submit">
  </form>

  <form action="" method="POST">
  {% csrf_token %}
  {{ article_form.as_p }}
  {% bootstrap_form form %}
    {% buttons %}
  <button type="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}
  </form>
{% endblock %}

web/backend/django/django-crud/articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block body %}
{% if request.resolver_match.url_name == 'create' %}
  <h1 class="text-center">글 작성하기</h1>
{% else %}
  <h1 class="text-center">글 수정하기</h1>
{% endif %}
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form article_form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock %} 

web/backend/django/django-crud/articles/templates/articles/hashtag.html
{% extends 'articles/base.html' %}

{% block body %}
<h1>{{ hashtag.content }}</h1>
{% for article in hashtag.articles.all %}
<a href="{% url 'articles:detail' article.pk %}">
<p>{{ article.title }}</p>
</a>
<p> article.title </p>
{% endfor %}
{% endblock body %}

web/backend/django/django-crud/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'articles/style.css'%}">
<style>
  tr>th:nth-of-type(2) {
    width: 50%;
  }
</style>
{% endblock css %}
{% block body %}
<img src="{% static 'articles/img.png'%}" alt="배경">
<h1>게시판에 오신걸 환영합니다.</h1>
<ol>
  {% if user.is_authenticated %}
  <a href="{% url 'articles:create' %}" class="btn btn-success">글 작성하기</a>
  <hr>
  {% endif %}
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">제목</th>
        <th scope="col">작성일자</th>
      </tr>
    </thead>
    <tbody>
      {% for article in articles %}
      <tr>
        <th scope="row">{{ article.id }}</th>
        <td>
          <a href="{% url 'articles:detail' article.pk %}">
            {{ article.title }}
          </a>
        </td>
        <td>{{ article.created_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endblock %}

web/backend/django/django-crud/articles/templates/articles/new.html
{% extends 'articles/base.html' %}
{% block body %}
  <h1>글 작성하기</h1>
  <form action="{% url 'articles:create' %}" method='POST'>
  {% csrf_token %}
  <div class="form-group">
    <label for="title">제목</label>
    <input name="title" type="text" class="form-control" id="title" aria-describedby="emailHelp" placeholder="제목을 입력하세요.">
    <small id="emailHelp" class="form-text text-muted">글의 제목을 작성 해주세요.</small>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">내용</label>
    <textarea name="content" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    {{ article_form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}
  </form>
{% endblock %}

web/backend/django/django-crud/articles/templates/articles/new2.html
{% extends 'articles/base.html' %}
{% block body %}
  <h1>글 작성하기</h1>
  <form action="{% url 'articles:create' %}" method='POST'>
  {% csrf_token %}
  <div class="form-group">
    <label for="title">제목</label>
    <input name="title" type="text" class="form-control" id="title" aria-describedby="emailHelp" placeholder="제목을 입력하세요.">
    <small id="emailHelp" class="form-text text-muted">글의 제목을 작성 해주세요.</small>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">내용</label>
    <textarea name="content" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

  <form action="" method="POST">
    {% csrf_token %}
    {{ article_form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}